spring:
  datasource:
    url: jdbc:h2:mem:probe-project-db
    connectionProperties: useUnicode=true;characterEncoding=utf-8;
    sqlScriptEncoding: utf-8
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    favicon:
      enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /probe-project/swagger-ui.html

scheduler-config:
  fixed-delay: 10000
  initial-delay: 10000