spring:
  datasource:
    url: jdbc:h2:mem:probe-project-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

springdoc:
  swagger-ui:
    path: /probe-project/swagger-ui.html