openapi: '3.0.0'
info:
  title: probe-project
  description: "probe-project for test testing"
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost

tags:
  - name: clients
    description: Клиенты
  - name: processes
    description: Процессы
  - name: processStatuses
    description: Статусы процесса
  - name: accountStatuses
    description: Статусы счета
  - name: currencies
    description: Справочник валют

paths:

  /clients:
    get:
      tags:
        - clients
      summary: Все клиенты
      description: Все клиенты
      operationId: getClients
      responses:
        200:
          description: Успешное получение всех клиентов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientListResponse'
        500:
          $ref: '#/components/responses/500'

  /clients/inn/{inn}:
    get:
      tags:
        - clients
      summary: Поиск клиента по инн
      description: Поиск клиента по инн
      operationId: findClientByInn
      parameters:
        - name: inn
          in: path
          description: ИНН клиента
          required: true
          schema:
            type: string
            minLength: 12
            maxLength: 12
      responses:
        200:
          description: Успешное получение клиента по инн
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /processes:
    post:
      tags:
        - processes
      summary: Создание нового процесса
      description: Создание нового процесса
      operationId: postProcess
      requestBody:
        description: Запрос для создания процесса
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ProcessRequest'
      responses:
        201:
          description: Успешное создание нового процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /processes/clients/{idClient}:
    get:
      tags:
        - processes
      summary: Все процессы клиента
      description: Все процессы клиента
      operationId: getAllClientProcesses
      parameters:
        - name: idClient
          in: path
          description: UUID клиента
          required: true
          schema:
            type: string
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            minLength: 36
            maxLength: 36
      responses:
        201:
          description: Успешное получение всех процессов клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessListResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /accounts/reserve:
    post:
      tags:
        - accounts
      summary: Резервирование нового счета
      description: Резервирование нового счета
      operationId: postAccountReserve
      requestBody:
        description: Запрос для резервирования счета
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AccountReserveRequest'
      responses:
        201:
          description: Успешное резервирование счета
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /accounts/open:
    patch:
      tags:
        - accounts
      summary: Открытие зарезервированных счетов
      description: Открытие зарезервированных счетов
      operationId: patchAccountOpen
      requestBody:
        description: Запрос для открытия зарезервированных счетов
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AccountOpenRequest'
      responses:
        201:
          description: Успешное запрос на открытие счетов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /accounts/clients/{idClient}:
    get:
      tags:
        - accounts
      summary: Все счета клиента
      description: Все счета клиента
      operationId: getAllClientAccounts
      parameters:
        - name: idClient
          in: path
          description: UUID клиента
          required: true
          schema:
            type: string
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            minLength: 36
            maxLength: 36
      responses:
        201:
          description: Успешное получение всех счетов клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /process-statuses:
    get:
      tags:
        - processStatuses
      summary: Получение списка всех возможных статусов процесса
      description: Получение списка всех возможных статусов процесса
      operationId: getAllProcessStatuses
      responses:
        200:
          description: Успешное получение списка всех возможных статусов процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessStatusListResponse'
        500:
          $ref: '#/components/responses/500'

  /account-statuses:
    get:
      tags:
        - accountStatuses
      summary: Получение списка всех возможных статусов счета
      description: Получение списка всех возможных статусов счета
      operationId: getAllAccountStatuses
      responses:
        200:
          description: Успешное получение списка всех возможных статусов счета
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountStatusListResponse'
        500:
          $ref: '#/components/responses/500'

  /dictionaries/currencies:
    get:
      tags:
        - currencies
      summary: Получение кодов валют
      description: Получение кодов валют
      operationId: getCurrencies
      responses:
        200:
          description: Успешное получение кодов валют
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyListResponse'
        500:
          $ref: '#/components/responses/500'

components:

  responses:

    200:
      description: OK
      content: { }

    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:

    Error:
      description: Описание ошибки
      type: object
      required:
        - errorCode
        - timestamp
      properties:
        errorCode:
          type: string
          description: Код ошибки
        timestamp:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время ошибки

    ClientResponse:
      type: object
      properties:
        idClient:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        fio:
          type: string
          maxLength: 100
        inn:
          type: string
          minLength: 12
          maxLength: 12

    ClientListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ClientResponse'

    ProcessRequest:
      type: object
      properties:
        idClient:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36

    ProcessResponse:
      type: object
      properties:
        idProcess:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        startDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время начала процесса
        lastUpdateDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время последнего обновления процесса
        processStatus:
          type: string
          maxLength: 30
          description: Статус процесса

    ProcessListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ProcessResponse'

    AccountReserveRequest:
      type: object
      properties:
        idClient:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        code:
          type: string
          maxLength: 3

    AccountOpenRequest:
      type: object
      properties:
        idClient:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36

    AccountResponse:
      type: object
      properties:
        idAccount:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        number:
          type: string
          maxLength: 20
          description: Номер счета
        currencyIso:
          type: string
          maxLength: 3
          description: ISO валюты
        clientFio:
          type: string
          maxLength: 100
        reservationDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время резервирования счета
        openingDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время начала открытия счета
        openDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время открытия счета
        accountStatus:
          type: string
          maxLength: 30
          description: Статус счета

    AccountListResponse:
      type: array
      items:
        $ref: '#/components/schemas/AccountResponse'

    ProcessStatusResponse:
      type: object
      properties:
        idProcessStatus:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        name:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 200

    ProcessStatusListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ProcessStatusResponse'

    AccountStatusResponse:
      type: object
      properties:
        idAccountStatus:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        name:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 200

    AccountStatusListResponse:
      type: array
      items:
        $ref: '#/components/schemas/AccountStatusResponse'

    CurrencyResponse:
      type: object
      properties:
        idCurrency:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        code:
          type: string
          maxLength: 3
        iso:
          type: string
          maxLength: 3
        name:
          type: string
          maxLength: 30

    CurrencyListResponse:
      type: array
      items:
        $ref: '#/components/schemas/CurrencyResponse'