openapi: '3.0.0'
info:
  title: probe-project
  description: "probe-project for test testing"
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost

tags:
  - name: admin
    description: Администрирование
  - name: clients
    description: Клиенты

paths:

  /admin/ping:
    get:
      tags:
        - admin
      summary: Проверка доступности сервиса
      description: Проверка доступности сервиса
      operationId: ping
      responses:
        200:
          description: Успешный ping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'

  /clients:
    get:
      tags:
        - clients
      summary: Все клиенты
      description: Все клиенты
      operationId: getClients
      responses:
        200:
          description: Успешное получение всех клиентов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientListResponse'
        500:
          $ref: '#/components/responses/500'

  /clients/inn/{inn}:
    get:
      tags:
        - clients
      summary: Поиск клиента по инн
      description: Поиск клиента по инн
      operationId: findClientByInn
      parameters:
        - name: inn
          in: path
          description: ИНН клиента
          required: true
          schema:
            type: string
            minLength: 12
            maxLength: 12
      responses:
        200:
          description: Успешное получение клиента по инн
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

components:

  responses:

    200:
      description: OK
      content: { }

    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:

    Error:
      description: Описание ошибки
      type: object
      required:
        - errorCode
        - timestamp
      properties:
        errorCode:
          type: string
          description: Код ошибки
        timestamp:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время ошибки

    PingResponse:
      type: object
      properties:
        result:
          type: string
        message:
          type: string

    ClientResponse:
      type: object
      properties:
        id:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        fio:
          type: string
          maxLength: 100
        inn:
          type: string
          minLength: 12
          maxLength: 12

    ClientListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ClientResponse'