openapi: '3.0.0'
info:
  title: probe-project
  description: "probe-project for test testing"
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost

tags:
  - name: admin
    description: Администрирование
  - name: clients
    description: Клиенты
  - name: processes
    description: Процессы
  - name: processStatuses
    description: Статусы процесса
  - name: accountStatuses
    description: Статусы счета

paths:

  /admin/ping:
    get:
      tags:
        - admin
      summary: Проверка доступности сервиса
      description: Проверка доступности сервиса
      operationId: ping
      responses:
        200:
          description: Успешный ping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'

  /clients:
    get:
      tags:
        - clients
      summary: Все клиенты
      description: Все клиенты
      operationId: getClients
      responses:
        200:
          description: Успешное получение всех клиентов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientListResponse'
        500:
          $ref: '#/components/responses/500'

  /clients/inn/{inn}:
    get:
      tags:
        - clients
      summary: Поиск клиента по инн
      description: Поиск клиента по инн
      operationId: findClientByInn
      parameters:
        - name: inn
          in: path
          description: ИНН клиента
          required: true
          schema:
            type: string
            minLength: 12
            maxLength: 12
      responses:
        200:
          description: Успешное получение клиента по инн
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /processes:
    post:
      tags:
        - processes
      summary: Создание нового процесса
      description: Создание нового процесса
      operationId: postProcess
      requestBody:
        description: Запрос для создания процесса
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ProcessRequest'
      responses:
        201:
          description: Успешное создание нового процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /processes/clients/{idClient}:
    get:
      tags:
        - processes
      summary: Все процессы клиента
      description: Все процессы клиента
      operationId: getAllClientProcesses
      parameters:
        - name: idClient
          in: path
          description: UUID клиента
          required: true
          schema:
            type: string
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            minLength: 36
            maxLength: 36
      responses:
        201:
          description: Успешное создание нового процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessListResponse'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /process-statuses:
    get:
      tags:
        - processStatuses
      summary: Получение списка всех возможных статусов процесса
      description: Получение списка всех возможных статусов процесса
      operationId: getAllProcessStatuses
      responses:
        200:
          description: Успешное получение списка всех возможных статусов процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessStatusListResponse'
        500:
          $ref: '#/components/responses/500'

  /account-statuses:
    get:
      tags:
        - accountStatuses
      summary: Получение списка всех возможных статусов счета
      description: Получение списка всех возможных статусов счета
      operationId: getAllAccountStatuses
      responses:
        200:
          description: Успешное получение списка всех возможных статусов счета
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountStatusListResponse'
        500:
          $ref: '#/components/responses/500'

components:

  responses:

    200:
      description: OK
      content: { }

    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:

    Error:
      description: Описание ошибки
      type: object
      required:
        - errorCode
        - timestamp
      properties:
        errorCode:
          type: string
          description: Код ошибки
        timestamp:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время ошибки

    PingResponse:
      type: object
      properties:
        result:
          type: string
        message:
          type: string

    ClientResponse:
      type: object
      properties:
        idClient:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        fio:
          type: string
          maxLength: 100
        inn:
          type: string
          minLength: 12
          maxLength: 12

    ClientListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ClientResponse'

    ProcessRequest:
      type: object
      properties:
        clientInn:
          type: string
          minLength: 12
          maxLength: 12

    ProcessResponse:
      type: object
      properties:
        idProcess:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        startDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время начала процесса
        lastUpdateDate:
          type: string
          format: date-time
          pattern: 'MM/DD/YYYY HH24:MI:SS'
          description: Дата и время последнего обновления процесса
        processStatus:
          type: string
          maxLength: 30
          description: Статус процесса

    ProcessListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ProcessResponse'

    ProcessStatusResponse:
      type: object
      properties:
        idProcessStatus:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        name:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 200

    ProcessStatusListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ProcessStatusResponse'

    AccountStatusResponse:
      type: object
      properties:
        idAccountStatus:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minLength: 36
          maxLength: 36
        name:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 200

    AccountStatusListResponse:
      type: array
      items:
        $ref: '#/components/schemas/AccountStatusResponse'