--ACCOUNTS
--Тестовые счета
INSERT INTO ACCOUNTS (ID_ACCOUNT, NUMBER, ID_CURRENCY, ID_CLIENT, RESERVATION_DATE, OPENING_DATE, ID_ACCOUNT_STATUS)
    VALUES (random_uuid(), '40702810XXXXXXXXXXXX', SELECT ID_CURRENCY FROM CURRENCIES WHERE CODE = '810',
    SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', null, null,
    SELECT ID_ACCOUNT_STATUS FROM ACCOUNT_STATUSES WHERE NAME = 'RESERVED');

INSERT INTO ACCOUNTS (ID_ACCOUNT, NUMBER, ID_CURRENCY, ID_CLIENT, RESERVATION_DATE, OPENING_DATE, ID_ACCOUNT_STATUS)
    VALUES (random_uuid(), '40702810XXXXXXXXXXXX', SELECT ID_CURRENCY FROM CURRENCIES WHERE CODE = '810',
    SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', null, null,
    SELECT ID_ACCOUNT_STATUS FROM ACCOUNT_STATUSES WHERE NAME = 'RESERVED');

INSERT INTO ACCOUNTS (ID_ACCOUNT, NUMBER, ID_CURRENCY, ID_CLIENT, RESERVATION_DATE, OPENING_DATE, ID_ACCOUNT_STATUS)
    VALUES (random_uuid(), '40702810XXXXXXXXXXXX', SELECT ID_CURRENCY FROM CURRENCIES WHERE CODE = '810',
    SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', null, null,
    SELECT ID_ACCOUNT_STATUS FROM ACCOUNT_STATUSES WHERE NAME = 'RESERVED');

INSERT INTO ACCOUNTS (ID_ACCOUNT, NUMBER, ID_CURRENCY, ID_CLIENT, RESERVATION_DATE, OPENING_DATE, ID_ACCOUNT_STATUS)
    VALUES (random_uuid(), '40702810XXXXXXXXXXXX', SELECT ID_CURRENCY FROM CURRENCIES WHERE CODE = '810',
    SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111112', null, null,
    SELECT ID_ACCOUNT_STATUS FROM ACCOUNT_STATUSES WHERE NAME = 'RESERVED');

INSERT INTO ACCOUNTS (ID_ACCOUNT, NUMBER, ID_CURRENCY, ID_CLIENT, RESERVATION_DATE, OPENING_DATE, ID_ACCOUNT_STATUS)
    VALUES (random_uuid(), '40702810XXXXXXXXXXXX', SELECT ID_CURRENCY FROM CURRENCIES WHERE CODE = '810',
    SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111112', null, null,
    SELECT ID_ACCOUNT_STATUS FROM ACCOUNT_STATUSES WHERE NAME = 'RESERVED');