--PROCESSES
--Тестовые счета
INSERT INTO PROCESSES (ID_PROCESS, ID_CLIENT, START_DATE, LAST_UPDATE_DATE, ID_PROCESS_STATUS)
    VALUES (random_uuid(), SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', now(), now(),
    SELECT ID_PROCESS_STATUS FROM PROCESS_STATUSES WHERE NAME = 'NEW');

INSERT INTO PROCESSES (ID_PROCESS, ID_CLIENT, START_DATE, LAST_UPDATE_DATE, ID_PROCESS_STATUS)
    VALUES (random_uuid(), SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', now(), now(),
    SELECT ID_PROCESS_STATUS FROM PROCESS_STATUSES WHERE NAME = 'NEW');

INSERT INTO PROCESSES (ID_PROCESS, ID_CLIENT, START_DATE, LAST_UPDATE_DATE, ID_PROCESS_STATUS)
    VALUES (random_uuid(), SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111111', now(), now(),
    SELECT ID_PROCESS_STATUS FROM PROCESS_STATUSES WHERE NAME = 'NEW');

INSERT INTO PROCESSES (ID_PROCESS, ID_CLIENT, START_DATE, LAST_UPDATE_DATE, ID_PROCESS_STATUS)
    VALUES (random_uuid(), SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111112', now(), now(),
    SELECT ID_PROCESS_STATUS FROM PROCESS_STATUSES WHERE NAME = 'COMPLIANCE_ERROR');

INSERT INTO PROCESSES (ID_PROCESS, ID_CLIENT, START_DATE, LAST_UPDATE_DATE, ID_PROCESS_STATUS)
    VALUES (random_uuid(), SELECT ID_CLIENT FROM CLIENTS WHERE INN = '111111111112', now(), now(),
    SELECT ID_PROCESS_STATUS FROM PROCESS_STATUSES WHERE NAME = 'DONE');